[package]
name = "traffic-light-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
traffic-light = {path="./../traffic-light/"}
local-ip-address = "0.4.9"